repos:
  - repo: git://github.com/golangci/golangci-lint
    rev: v1.38.0
    hooks:
      - id: golangci-lint

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-json
        exclude: ^build/
      - id: check-merge-conflict
      - id: check-yaml
        exclude: ^build/
      - id: detect-private-key
      - id: trailing-whitespace
        exclude: ^build/

  - repo: git://github.com/igorshubovych/markdownlint-cli
    rev: v0.26.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
        stages: [commit]
